language: node_js
node_js:
- 'stable'
install:
- yarn install

jobs:
    include:
    - stage: Test
      script:
        - yarn test --watchAll=false -- --coverage && npx codecov
    - stage: Build
      script:
        - yarn build
        - yarn build-storybook
    - stage: GithubPage
      if: branch = master
      script:
        - yarn build-storybook
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: storybook-static
        on:
          branch: master
